### ISSUE TITLE
Implement UniFormItem helper

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter.Uniform#2]
Implement UniFormItem helper for the custom element `<uni-form-item>` (development of which is tracked in https://github.com/Starcounter/RebelsLounge/issues/261)

UniFormItem can be used for:

- read-only rendering of a single view-model property with a label, value, and a message
- editable rendering of a single view-model property with a label, value, validation result and output (that can be a neutral message, positive validation result, negative validation result)

The view-model property can be bound to database object property.

cc @joozek78

**Comment by warpech** [comment]
This is being implemented in https://github.com/Starcounter/Starcounter.Uniform/pull/6

**Comment by PatrykSzwer** [comment]
Done in #6.
