### ISSUE TITLE
Unit tests won't work with recent changes to the packages

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Starcounter.Uniform#24]
@miyconst after your PR: https://github.com/Starcounter/Starcounter.Uniform/pull/23 seems like something broke in the unit tests/NUnit. I can't run unit tests (all become yellow - inconclusive) and I can see an error:
![image](https://user-images.githubusercontent.com/25042256/55644248-9f133f00-57d5-11e9-824d-0b1293c5ea5a.png)
(last words mean that there is no implementation for that method).

@miyconst could you take a look please?

**Comment by miyconst** [comment]
@PatrykSzwer can you please provide Starcounter & Visual Studio versions?

Here is my setup:

- Starcounter `2.4.990.257`.
- Visual Studio `15.9.10`.

![image](https://user-images.githubusercontent.com/6435556/55683519-f124a380-5940-11e9-80de-280d5e0ffd4e.png)

**Comment by PatrykSzwer** [comment]
I updated my VS (since I had some old version, like 15.8.9 or something like this) and then I had some different errors related to processor architecture, selected build options etc. I fixed those and tests started working again. Thanks for help @miyconst, closing this one.
